// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanAllCache() {
  return window['go']['main']['App']['CleanAllCache']();
}

export function CleanDownloadCache() {
  return window['go']['main']['App']['CleanDownloadCache']();
}

export function CleanModule(arg1, arg2) {
  return window['go']['main']['App']['CleanModule'](arg1, arg2);
}

export function CleanModuleCache() {
  return window['go']['main']['App']['CleanModuleCache']();
}

export function DiagnoseEnv() {
  return window['go']['main']['App']['DiagnoseEnv']();
}

export function FixGoProxy() {
  return window['go']['main']['App']['FixGoProxy']();
}

export function FixGoRoot(arg1) {
  return window['go']['main']['App']['FixGoRoot'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentGoPath() {
  return window['go']['main']['App']['GetCurrentGoPath']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetEnvInfo() {
  return window['go']['main']['App']['GetEnvInfo']();
}

export function GetGoPathMode() {
  return window['go']['main']['App']['GetGoPathMode']();
}

export function GetInstallSettings() {
  return window['go']['main']['App']['GetInstallSettings']();
}

export function GetInstalledVersions() {
  return window['go']['main']['App']['GetInstalledVersions']();
}

export function GetLatestStableVersion() {
  return window['go']['main']['App']['GetLatestStableVersion']();
}

export function GetMirrorOptions() {
  return window['go']['main']['App']['GetMirrorOptions']();
}

export function GetModuleCachePath() {
  return window['go']['main']['App']['GetModuleCachePath']();
}

export function GetModuleCacheStats() {
  return window['go']['main']['App']['GetModuleCacheStats']();
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function GetPackage(arg1, arg2) {
  return window['go']['main']['App']['GetPackage'](arg1, arg2);
}

export function GetRemoteVersions(arg1) {
  return window['go']['main']['App']['GetRemoteVersions'](arg1);
}

export function GetSharedGoPath() {
  return window['go']['main']['App']['GetSharedGoPath']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function InstallVersion(arg1, arg2) {
  return window['go']['main']['App']['InstallVersion'](arg1, arg2);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function SearchPackages(arg1) {
  return window['go']['main']['App']['SearchPackages'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SetEnvVar(arg1, arg2) {
  return window['go']['main']['App']['SetEnvVar'](arg1, arg2);
}

export function SetGoPathMode(arg1) {
  return window['go']['main']['App']['SetGoPathMode'](arg1);
}

export function SetGoProxy(arg1) {
  return window['go']['main']['App']['SetGoProxy'](arg1);
}

export function SetInstallSettings(arg1, arg2) {
  return window['go']['main']['App']['SetInstallSettings'](arg1, arg2);
}

export function SetMirror(arg1) {
  return window['go']['main']['App']['SetMirror'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['main']['App']['SetProxy'](arg1);
}

export function SetSharedGoPath(arg1) {
  return window['go']['main']['App']['SetSharedGoPath'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function UninstallVersion(arg1) {
  return window['go']['main']['App']['UninstallVersion'](arg1);
}

export function UseVersion(arg1) {
  return window['go']['main']['App']['UseVersion'](arg1);
}

export function VerifyModules() {
  return window['go']['main']['App']['VerifyModules']();
}
