// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {env} from '../models';
import {cache} from '../models';
import {config} from '../models';
import {main} from '../models';
import {version} from '../models';
import {module} from '../models';

export function CleanAllCache():Promise<void>;

export function CleanDownloadCache():Promise<void>;

export function CleanModule(arg1:string,arg2:string):Promise<void>;

export function CleanModuleCache():Promise<void>;

export function DiagnoseEnv():Promise<Array<env.DiagnoseResult>>;

export function FixGoProxy():Promise<void>;

export function FixGoRoot(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetCacheInfo():Promise<cache.CacheInfo>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentGoPath():Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function GetEnvInfo():Promise<env.EnvInfo>;

export function GetGoPathMode():Promise<string>;

export function GetInstallSettings():Promise<main.InstallSettings>;

export function GetInstalledVersions():Promise<Array<version.InstalledVersion>>;

export function GetLatestStableVersion():Promise<string>;

export function GetMirrorOptions():Promise<Array<config.MirrorOption>>;

export function GetModuleCachePath():Promise<string>;

export function GetModuleCacheStats():Promise<module.ModuleCacheStats>;

export function GetModules():Promise<Array<module.ModuleInfo>>;

export function GetPackage(arg1:string,arg2:string):Promise<void>;

export function GetRemoteVersions(arg1:boolean):Promise<Array<version.GoVersion>>;

export function GetSharedGoPath():Promise<string>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function InstallPackage(arg1:string):Promise<void>;

export function InstallVersion(arg1:string,arg2:string):Promise<void>;

export function ResetConfig():Promise<void>;

export function SearchPackages(arg1:string):Promise<Array<module.SearchResult>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetEnvVar(arg1:string,arg2:string):Promise<void>;

export function SetGoPathMode(arg1:string):Promise<void>;

export function SetGoProxy(arg1:string):Promise<void>;

export function SetInstallSettings(arg1:string,arg2:string):Promise<void>;

export function SetMirror(arg1:string):Promise<void>;

export function SetProxy(arg1:string):Promise<void>;

export function SetSharedGoPath(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function UninstallVersion(arg1:string):Promise<void>;

export function UseVersion(arg1:string):Promise<void>;

export function VerifyModules():Promise<Array<module.VerifyResult>>;
